version: 2

sources:
  - name: pharma
    database: PHARMA_DB
    schema: P_RAW_SCH  # Raw data schema
    tables:
      - name: DOCTORS
      - name: DRUGS
      - name: INVENTORY
      - name: MANUFACTURERS
      - name: PATIENTS
      - name: PHARMACIES
      - name: PRESCRIPTIONS
      - name: PRESCRIPTION_ITEMS
